export interface Cat {
    _id: string,
    name: string,
    slug: string,
    main: boolean,
    odia: string,
    isActive: boolean,
    metaTitle: string,
    metaDescription: string,
    __v: number,
    metaTitleOdia: string,
    metaDescriptionOdia: string,
    metaKeywords: string,
    hasPosts: [],
    postCount: number,
    hasActivePosts: boolean
}
export interface BreakingNews {
    _id: string,
    language: string,
    title: string,
    authors: boolean,
    isActive: boolean,
    publishedTime: string,
    uid: string,
    __v: number,
}

export interface Post{
      _id: string,
      language: string,
      postType: string,
      isSpecial: boolean,
      videoUrl:string ,
      title: string,
      highlights: string,
      location: string,
      body: string,
      selectCategory: string,
      isBreaking: boolean,
      category: Cat[],
      authors: string,
      publishedTime: string,
      metaTitle: string,
      metaDescription: string,
      articleSource: string,
      url: string,
      slug: string,
      status: boolean,
      scheduledTime: string,
      views: number,
      content: string,
      position: number,
      assets: [],
      prefix: string,
      keywords: [],
      uid: string,
      __v: number,
      thumbnail: string,
      id: string
}
