import type { Metadata } from "next";
import "./globals.css"
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import {Provider} from "@/components/Provider/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <main>
          <Provider>
            <Header />
            {children}
            <Footer />
          </Provider>
        </main>
      </body>
    </html>
  );
}
