export interface Cat {
    name: string,
    slug: string,
    main: boolean,
    odia: string,
    isActive: boolean,
    metaTitle: string,
    metaDescription: string,
    metaTitleOdia: string,
    metaDescriptionOdia: string,
    metaKeywords: string,
    hasPosts: [],
    postCount: number,
    hasActivePosts: boolean
}
export interface BreakingNews {
    language: string,
    title: string,
    authors: [string],
    isActive: boolean,
    publishedTime: string,
    uid: string,
}

export interface Post{
      language: string,
      postType: string,
      isSpecial: boolean,
      videoUrl:string ,
      title: string,
      highlights: string,
      location: string,
      body: string,
      selectCategory: string,
      isBreaking: boolean,
      category: Cat[],
      authors: [string],
      publishedTime: string,
      metaTitle: string,
      metaDescription: string,
      articleSource: string,
      url: string,
      slug: string,
      status: string,
      scheduledTime: string,
      views: number,
      content: string,
      position: number,
      assets: [string],
      prefix: string,
      keywords: [string],
      uid: string,
      thumbnail: string,
}

export interface AdsContextType {
    brand_name: string,
    advetisement_name: string,
    ad_platform: string,
    ad_type: string,
    ad_link: string,
    daily_impression_limit: number,
    schedule: string,
    status: string,
    ad_image: string,
    language: string,
    publish: Date
}
